# Generated by Django 5.0.6 on 2025-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.IntegerField(),
        ),
    ]
